In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing dataset

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/Classroom/X-IIoTID dataset.csv')

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (1,3,5,12,24) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [ ]:
dataset.columns

Index(['Date', 'Timestamp', 'Scr_IP', 'Scr_port', 'Des_IP', 'Des_port',
       'Protocol', 'Service', 'Duration', 'Scr_bytes', 'Des_bytes',
       'Conn_state', 'missed_bytes', 'is_syn_only', 'Is_SYN_ACK',
       'is_pure_ack', 'is_with_payload', 'FIN or RST', 'Bad_checksum',
       'is_SYN_with_RST', 'Scr_pkts', 'Scr_ip_bytes', 'Des_pkts',
       'Des_ip_bytes', 'anomaly_alert', 'total_bytes', 'total_packet',
       'paket_rate', 'byte_rate', 'Scr_packts_ratio', 'Des_pkts_ratio',
       'Scr_bytes_ratio', 'Des_bytes_ratio', 'Avg_user_time', 'Std_user_time',
       'Avg_nice_time', 'Std_nice_time', 'Avg_system_time', 'Std_system_time',
       'Avg_iowait_time', 'Std_iowait_time', 'Avg_ideal_time',
       'Std_ideal_time', 'Avg_tps', 'Std_tps', 'Avg_rtps', 'Std_rtps',
       'Avg_wtps', 'Std_wtps', 'Avg_ldavg_1', 'Std_ldavg_1', 'Avg_kbmemused',
       'Std_kbmemused', 'Avg_num_Proc/s', 'Std_num_proc/s', 'Avg_num_cswch/s',
       'std_num_cswch/s', 'OSSEC_alert', 'OSSEC_alert_level', 'Lo

## Performing label encoding on the categorical columns

In [ ]:
categorical_columns = ['Date','Des_IP','Protocol','Service','class1','class2','class3','is_syn_only', 'Is_SYN_ACK','Scr_IP',
       'is_pure_ack', 'is_with_payload', 'FIN or RST', 'Bad_checksum',
       'is_SYN_with_RST','anomaly_alert']

In [ ]:
# Import label encoder
from sklearn import preprocessing
  
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
for col in categorical_columns:
  dataset[col]=dataset[col].astype(str)
  dataset[col]=label_encoder.fit_transform(dataset[col])

## Filling null values with mean

In [ ]:
def is_float(element: any) -> bool:
    #If you expect None to be passed:
    if element is None: 
        return False
    try:
        float(element)
        return True
    except ValueError:
        return False

dataset=dataset.replace('?',np.nan)
dataset=dataset.replace('-',np.nan)

for col in dataset.columns:
  dataset=dataset[dataset[col].apply(lambda x: is_float(str(x)))]
  if dataset[col].dtype == 'object':
    dataset[col]=dataset[col].astype(float)
  dataset[col]=dataset[col].fillna(dataset[col].mean())

## Defining features and target value

In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting train and test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

## Performing Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Getting results for RF, SVC, DT Classifiers

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
classifiers = [
    RandomForestClassifier(),
    SVC(),
    DecisionTreeClassifier()
]

##Accuracy calculation for RF, SVC, DT classifiers

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
i=0
for classifier in classifiers:
  classifier.fit(X_train,y_train)
  y_pred= classifier.predict(X_test)
  print("Metrices for "+str(classifiers[i]))
  cm = confusion_matrix(y_test, y_pred)
  print("Confusion Matrix:")
  print(cm)
  print("Accuracy:")
  print(accuracy_score(y_test, y_pred))
  i=i+1

Metrices for RandomForestClassifier()
Confusion Matrix:
[[79781     0]
 [    0 84256]]
Accuracy:
1.0
Metrices for SVC()
Confusion Matrix:
[[79734    47]
 [    6 84250]]
Accuracy:
0.9996769021623171
Metrices for DecisionTreeClassifier()
Confusion Matrix:
[[79781     0]
 [    0 84256]]
Accuracy:
1.0


In [ ]:
from google.colab import files
files.download('/content/drive/MyDrive/Classroom/X-IIoTID dataset.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
dataset.to_csv('C:\Users\Apoorv\OneDrive\Documents\preprocess.csv', sep='\t')

SyntaxError: ignored

In [ ]:
dataset.to_csv('C:\Users\Apoorv\OneDrive\Documents\preprocess.csv', sep='\t')

SyntaxError: ignored

In [ ]:
dataset.to_csv('C:\Users\Apoorv\OneDrive\Documents\preprocess.csv', sep='\t')

SyntaxError: ignored

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/Classroom/X-IIoTID dataset.csv')


/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (1,3,5,12,24) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [ ]:
dataset.to_csv(r"C:\Users\Apoorv\OneDrive\Documents\preprocessed.csv', sep='\t")

In [ ]:
dataset.to_csv(r"C:\Users\Apoorv\OneDrive\Documents\preprocessed.csv', sep='\t")

In [ ]:
dataset.to_csv(r"C:\Users\Apoorv\OneDrive\Documents\preprocessed.csv", sep='\t')